DROP SEQUENCE ORGANIZATOR_ID_SEQ;
DROP SEQUENCE MODNA_REVIJA_RBR_SEQ;

DROP TABLE IMENA_VLASNIKA;
DROP TABLE SPECIJALNI_GOSTI;
DROP TABLE PREDSTAVLJA;
DROP TABLE NASTUPA_U;
DROP TABLE NAZIVI_CASOPISA;
DROP TABLE NAZIVI_ZEMALJA;
DROP TABLE MODNA_REVIJA;
DROP TABLE MODNI_KREATOR;
DROP TABLE MANEKEN;
DROP TABLE MODNA_AGENCIJA;
DROP TABLE MODNA_KUCA;
DROP TABLE ORGANIZATOR;