CREATE SEQUENCE MODNA_REVIJA_RBR_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999999999999999999999999999
    CACHE 20
    NOORDER
    NOCYCLE;


CREATE SEQUENCE ORGANIZATOR_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999999999999999999999999999
    CACHE 20
    NOORDER
    NOCYCLE;
    
SET DEFINE OFF;

CREATE OR REPLACE TRIGGER MODNA_REVIJA_AUTO_PK
    BEFORE INSERT
    ON MODNA_REVIJA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT MODNA_REVIJA_RBR_SEQ.NEXTVAL INTO:NEW.RBR_REVIJE FROM DUAL;
END;
ALTER TRIGGER MODNA_REVIJA_AUTO_PK ENABLE;

CREATE OR REPLACE TRIGGER ORGANIZATOR_AUTO_PK
    BEFORE INSERT
    ON ORGANIZATOR
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT ORGANIZATOR_ID_SEQ.NEXTVAL INTO:NEW.ID FROM DUAL;
END;
ALTER TRIGGER ORGANIZATOR_AUTO_PK ENABLE;