CREATE TABLE MANEKEN(
    MBR VARCHAR2(13)PRIMARY KEY,
    LICNO_IME VARCHAR2(15) NOT NULL,
    PREZIME VARCHAR2(15) NOT NULL,
    DATUM_RODJENJA DATE,
    POL VARCHAR2(1) NOT NULL,
    VISINA NUMBER(3,0),
    TEZINA NUMBER(4,1),
    BOJA_OCIJU VARCHAR2(10),
    BOJA_KOSE VARCHAR2(10),
    KONFEKCIJSKI_BROJ VARCHAR2(4),
    ZANIMANJE VARCHAR2(15),
    CHECK(LENGTH(MBR)=13),
    CHECK(REGEXP_LIKE(MBR, '^[0-9]+$'))
);

CREATE TABLE MODNI_KREATOR(
    MBR VARCHAR2(13)PRIMARY KEY,
    LICNO_IME VARCHAR2(15) NOT NULL,
    PREZIME VARCHAR2(15) NOT NULL,
    DATUM_RODJENJA DATE,
    POL VARCHAR2(1) NOT NULL,
    ZEMLJA_POREKLA VARCHAR2(30),
    CHECK(LENGTH(MBR)=13),
    CHECK(REGEXP_LIKE(MBR, '^[0-9]+$'))
);

CREATE TABLE MODNA_KUCA(
    NAZIV VARCHAR2(30) PRIMARY KEY,
    OSNIVAC_LICNO_IME VARCHAR2(15) NOT NULL,
    OSNIVAC_PREZIME VARCHAR2(15) NOT NULL,
    DRZAVA VARCHAR2(30),
    GRAD VARCHAR2(20),
    ULICA VARCHAR2(30)
);

CREATE TABLE MODNA_REVIJA(
    RBR_REVIJE NUMBER PRIMARY KEY,
    NAZIV VARCHAR2(30) NOT NULL,
    DRZAVA VARCHAR2(30),
    GRAD VARCHAR2(20),
    ULICA VARCHAR2(30),
    TERMIN_ODRZAVANJA TIMESTAMP,
    CHECK (RBR_REVIJE>0)
);

CREATE TABLE MODNA_AGENCIJA(
    PIB VARCHAR2(8) PRIMARY KEY,
    NAZIV VARCHAR2(30) NOT NULL,
    INOSTRANA VARCHAR2(1) NOT NULL,
    DRZAVA VARCHAR2(30),
    GRAD VARCHAR2(20),
    ULICA VARCHAR2(30),
    DATUM_OSNIVANJA DATE,
    CHECK(LENGTH(PIB)=8),
    CHECK(REGEXP_LIKE(PIB, '^[0-9]+$'))
);

CREATE TABLE ORGANIZATOR(
    ID NUMBER PRIMARY KEY,
    PRVA_REVIJA VARCHAR2(1),
    INFORMACIJE_O_KOLEKCIJI VARCHAR2(256)
);

ALTER TABLE MANEKEN ADD PIB_AGENCIJE VARCHAR2(8);
ALTER TABLE MANEKEN ADD CONSTRAINT PIB_L_CHECK CHECK(LENGTH(PIB_AGENCIJE)=8);
ALTER TABLE MANEKEN ADD CONSTRAINT PIB_FK FOREIGN KEY(PIB_AGENCIJE) REFERENCES MODNA_AGENCIJA(PIB);

ALTER TABLE MODNI_KREATOR ADD ORGANIZATOR_ID NUMBER;
ALTER TABLE MODNI_KREATOR ADD CONSTRAINT FK_ORGANIZATOR_KREATOR FOREIGN KEY(ORGANIZATOR_ID) REFERENCES ORGANIZATOR(ID);
ALTER TABLE MODNI_KREATOR ADD NAZIV_KUCE VARCHAR2(30);
ALTER TABLE MODNI_KREATOR ADD CONSTRAINT FK_MODNA_KUCA FOREIGN KEY(NAZIV_KUCE) REFERENCES MODNA_KUCA(NAZIV);

ALTER TABLE MODNA_KUCA ADD ORGANIZATOR_ID NUMBER;
ALTER TABLE MODNA_KUCA ADD CONSTRAINT FK_ORGANIZATOR_KUCA FOREIGN KEY(ORGANIZATOR_ID) REFERENCES ORGANIZATOR(ID);

ALTER TABLE MODNA_REVIJA ADD ORGANIZATOR_ID NUMBER;
ALTER TABLE MODNA_REVIJA ADD CONSTRAINT FK_ORGANIZATOR_REVIJA FOREIGN KEY(ORGANIZATOR_ID) REFERENCES ORGANIZATOR(ID);

CREATE TABLE NASTUPA_U(
    MBR_MANEKENA VARCHAR2(13) NOT NULL,
    RBR_REVIJE NUMBER NOT NULL,
    CHECK(LENGTH(MBR_MANEKENA)=13),
    CHECK(RBR_REVIJE>0),
    CONSTRAINT PK_NASTUPA_U PRIMARY KEY(MBR_MANEKENA, RBR_REVIJE),
    CONSTRAINT FK_NASTUPA_MANEKEN FOREIGN KEY(MBR_MANEKENA) REFERENCES MANEKEN(MBR),
    CONSTRAINT FK_NASTUPA_REVIJA FOREIGN KEY(RBR_REVIJE) REFERENCES MODNA_REVIJA(RBR_REVIJE)
);

CREATE TABLE PREDSTAVLJA(
    MBR_KREATORA VARCHAR2(13) NOT NULL,
    RBR_REVIJE NUMBER NOT NULL,
    CHECK(LENGTH(MBR_KREATORA)=13),
    CHECK(RBR_REVIJE>0),
    CONSTRAINT PK_PREDSTAVLJA PRIMARY KEY(MBR_KREATORA, RBR_REVIJE),
    CONSTRAINT FK_PREDSTAVLJA_KREATOR FOREIGN KEY(MBR_KREATORA) REFERENCES MODNI_KREATOR(MBR),
    CONSTRAINT FK_PREDSTAVLJA_REVIJA FOREIGN KEY(RBR_REVIJE) REFERENCES MODNA_REVIJA(RBR_REVIJE)
);

CREATE TABLE NAZIVI_CASOPISA(
    MBR_MANEKENA VARCHAR2(13) NOT NULL,
    NAZIV_CASOPISA VARCHAR2(30) NOT NULL,
    CHECK(LENGTH(MBR_MANEKENA)=13),
    CONSTRAINT PK_NAZIV_CASOPISA PRIMARY KEY(MBR_MANEKENA, NAZIV_CASOPISA),
    CONSTRAINT FK_NAZIV_CASOPISA_MANEKEN FOREIGN KEY(MBR_MANEKENA) REFERENCES MANEKEN(MBR)
);

CREATE TABLE NAZIVI_ZEMALJA(
    PIB_INOSTRANE VARCHAR2(8) NOT NULL,
    NAZIV_ZEMLJE VARCHAR2(30) NOT NULL,
    CHECK(LENGTH(PIB_INOSTRANE)=8),
    CONSTRAINT PK_Naziv_Zemlje PRIMARY KEY(PIB_INOSTRANE, NAZIV_ZEMLJE),
    CONSTRAINT FK_Naziv_Zemlje_Agencija FOREIGN KEY(PIB_INOSTRANE) REFERENCES MODNA_AGENCIJA(PIB)   
);

CREATE TABLE IMENA_VLASNIKA(
    NAZIV_KUCE VARCHAR2(30) NOT NULL,
    LICNO_IME VARCHAR2(15) NOT NULL,
    PREZIME VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_IMENA_VLASNIKA PRIMARY KEY(NAZIV_KUCE, LICNO_IME, PREZIME),
    CONSTRAINT FK_IMENA_VLASNIKA_KUCE FOREIGN KEY(NAZIV_KUCE) REFERENCES MODNA_KUCA(NAZIV)
);

CREATE TABLE SPECIJALNI_GOSTI(
    MBR_KREATORA VARCHAR2(13) NOT NULL,
    ORGANIZATOR_ID NUMBER NOT NULL,
    RBR_REVIJE NUMBER NOT NULL,
    CHECK(LENGTH(MBR_KREATORA)=13),
    CHECK(RBR_REVIJE>0),
    CONSTRAINT PK_SPECIJALNI_GOST PRIMARY KEY(MBR_KREATORA, ORGANIZATOR_ID, RBR_REVIJE),
    CONSTRAINT FK_SPECIJALNI_GOST_KREATORA FOREIGN KEY(MBR_KREATORA) REFERENCES MODNI_KREATOR(MBR),
    CONSTRAINT FK_SPECIJALNI_GOST_ORGANIZATOR FOREIGN KEY(ORGANIZATOR_ID) REFERENCES ORGANIZATOR(ID),
    CONSTRAINT FK_SPECIJALNI_GOST_REVIJA FOREIGN KEY(RBR_REVIJE) REFERENCES MODNA_REVIJA(RBR_REVIJE)
);